spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.qejadbzbjfcauyqzgjcw
spring.datasource.password=Jobhunter162006@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
###

###
#Config Jwt

jwt.base64-secret=qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==

jwt.access-token-validity-in-seconds=8640000
jwt.refresh-token-validity-in-seconds=8640000

#config upload file
###
#default = 1MB
spring.servlet.multipart.max-file-size=50MB

#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB

#base path
thang.upload-file.base-uri=file:///C:/Users/ADMIN/javaSpring/upload/
###

###
#config pagination
#start page = 1 not 0
spring.data.web.pageable.one-indexed-parameters=true

###
#config email with gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quocthangngo2006@gmail.com
spring.mail.password=lmazocefvedemtkc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

##
#key api-gemini
groq.api.key=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

